import = ["~/.config/alacritty/dracula.toml"]

[colors]
draw_bold_text_with_bright_colors = false

[env]
TERM = "xterm-256color"

[font]
size = 12.5

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "SemiBold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Regular Italic"

[font.normal]
family = "JetBrains Mono"
style = "Medium"

[font.offset]
y = 1

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "T"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control"

[window]
decorations = "none"
startup_mode = "Fullscreen"

[window.padding]
x = 20
y = 20
